### ISSUE TITLE
Typing doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by brentdax** [garglk/garglk#232]
On macOS Sierra, Gargoyle does not respond to letter keys. Arrow keys and mouse clicks continue to work as before.

**Comment by salty-horse** [comment]
Are you using a released version, or compiling your own? (I can't really help, just asking for more info :)

**Comment by brentdax** [comment]
I'm using the released version of Gargoyle 2011.1.

**Comment by Leareth9** [comment]
Same issue here.

**Comment by erkyrath** [comment]
I gave building it a quick shot on 10.12, but failed badly.

- I don't have the complete set of dylibs installed in one place.
- For building with the current SDK, ppc is not supported, so I had to comment out the ALTARCH lines in Jamrules. (Turning off UNIVERSAL might also have worked; didn't try that.)

It looks doable but I don't have the time to work it through this weekend.

**Comment by erkyrath** [comment]
I got it to build, using the latest versions of all the libraries (via homebrew). The app runs but the input bug is still there. Sorry.

**Comment by salty-horse** [comment]
Thanks for testing.

If anyone wants to take a closer look, perhaps start by seeing if `winkey()` processes KeyDown events correctly in `sysmac.m`. Specifically in the call to `CFStringGetBytes`.

**Comment by erkyrath** [comment]
Does anyone know if it's possible to run one of the compiled interpreters (glulxe) from the command line? The way this build is set up, I can't use Xcode's debugging tools, and I can't run it from the command line to do old-school debugging either.

**Comment by erkyrath** [comment]
...I can do `setenv GargoyleApp com.googlecode.garglk` followed by `build/macosx.release/glulxe/glulxe Advent.ulx`, but this get stuck in an infinite loop of `Glk library error: clear_selection: mask not initialized`.

**Comment by salty-horse** [comment]
I'm on Linux, so I'm not sure if this is helpful:
From your path it seems you're running a release builld.
if I build the project with `STATIC=1 BUILD=DEBUG jam` I can run the individual terps in gdb.

**Comment by kerrymg** [comment]
I have submitted a PR with a possible workaround for the macOS 10.12 input problem. The PR has a description of what the problem is (I could add it to this thread also).

I managed to use Xcode debugger by creating a dummy project and attaching to already running instances of Gargoyle and $(interpreter) processes. To debug interpreters you should disable Xcode's trapping of SIGUSR1 signal; this is how Gargoyle communicates to the interpreter process (from memory: `process handle SIGUSR1 -s false -n false -p true`).

The environment variable should be `com.googlecode.garglk-$(Gargoyle pid)` The pid is 4 hex numbers.

**Comment by brentdax** [comment]
For reference, the PR is #234.

**Comment by erkyrath** [comment]
PR seems to work -- I tested it in my build.

**Comment by kerrymg** [comment]
How to launch individual interpreters directly from macOS Terminal:

* Set environment variable GARGLK_INI so interpreter can find font files: `export GARGLK_INI=<full path to bundle Resources dir>`.
* Run Gargoyle (`open ./Gargoyle.app`) and cancel the open dialog (Gargoyle should remain running). Get its process id and convert it to a 4-character hex number, lowercase letters.
* Set GargoyleApp environment variable for interpreter to find the remote connection: `export GargoyleApp=com.googlecode.garglk-<pid>` where &lt;pid&gt; is hex number from previous step.
* Finally, run the interpreter executable passing it a story file name. `./Gargoyle.app/Contents/PlugIns/git <filename>`. The &lt;filename&gt; must be the full path to the file.

This works with my current CMake/Homebrew build setup.

**Comment by wmodes** [comment]
If the workaround works on previous versions of OSX, could we get it in a new release build? I also tried to build and it failed messily, so I'm not excited to try again.

**Comment by cspiegel** [comment]
Fixed by #234.

**Comment by wmodes** [comment]
Does that mean we got a new release build?

**Comment by lexaay** [comment]
I have the same question - is it possible to get a new release build? I'm trying to get my students in an interactive storytelling class to play Alabaster, but the current Gargoyle hangs with no input, and Zoom also crashes... thanks!

**Comment by erkyrath** [comment]
There has not been a new release, but see https://github.com/erkyrath/garglk/releases for an updated build.

**Comment by wmodes** [comment]
Andrew,

A few of us have tried the build and failed due to uh.. library issues, I can’t quite remember. But the build failed due to reasons I was unable to work around. 

It would be really great to have another build without the invisible text problem on OS X post Sierra. 

--
Wes Modes
A Secret History of American River People
http://peopleriverhistory.us

**Comment by dustinlacewell-wk** [comment]
I'm sad to see this still an issue after so much time and all that needs to happen is a release.

**Comment by poetcsw** [comment]
This really should be solved. There are no other up-to-date players for macOS. Not sure how to get things moving again.

**Comment by wmodes** [comment]
Agree. All my build attempts have failed. Sad face. 

--
Wes Modes
A Secret History of American River People
http://peoplesriverhistory.us

**Comment by rvdpluijm** [comment]
Still doesn't work... And Zoom isn't really my cup of tea...

**Comment by erkyrath** [comment]
Could someone paste in the error shown by the build I posted above?

**Comment by rvdpluijm** [comment]
> Could someone paste in the error shown by the build I posted above?

I just tried to use your particular build (the one referenced under releases, the first entry under pre-release) and I am suddenly again able to type (admittedly only tested under one particular story, but I imagine it should work with the rest also!). Used the binary package version.
